# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AIPartnerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'

  # Pods for AIGC-Examples

   use_frameworks!

    pod "AgoraAIGCService", :path => 'AIGCService_Binary.podspec'
    pod "AgoraComponetLog"
    #pod "sdk", :path => 'sdk.podspec'
    pod 'AgoraRtcEngine_Special_iOS', '4.1.1.24'
    pod 'RTMTokenBuilder', "1.0.2"
#    pod 'YYText'
    pod 'SVProgressHUD'
    
end
